# Generated by Django 5.2.1 on 2025-06-02 00:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='ciudadano',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='comentarios',
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='comentario_operario',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='operario_asignado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asignaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_ruta', 'En ruta'), ('completada', 'Completada')], default='pendiente', max_length=20),
        ),
        migrations.DeleteModel(
            name='Ciudadano',
        ),
    ]
